source 'https://rubygems.org'

# ruby '2.3.4'

gem 'pry'
gem 'pry-rails'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'pry-doc'
gem 'pry-docmore'
gem 'pry-byebug'
# gem 'httplog'
gem 'table_print'
gem 'rest-client'
gem 'faraday'
gem 'capybara-selenium'
gem 'capybara'
gem 'chromedriver-helper'
gem 'activesupport', require: 'active_support/all'
gem 'selenium', require: 'selenium/webdriver'
